### ISSUE TITLE
Okay guys, new issues 

### ISSUE THREAD

**Issue by RanHackett** [arcusmaximus/YTSubConverter#6] opened 2019-08-29 12:46 UTC
[Chocomint.txt](https://github.com/arcusmaximus/YTSubConverter/files/3555519/Chocomint.txt)

So, there is some code that gets left out of the file {\fad}, went upload it doesn't do its job. Which is weird since my cap got a lot of {\fad} in it, and there's only 3 that got corrupted , plus a bunch of random space in the cap (the final Ice, ice, ice part), idk if this is normal since I do use {\move}

Oh, and I try Fiddler out and still don't get how you suppose to "view" the YTT. Hope you guys can help me out~:heart:

**Comment by nyaasar** [comment] 2019-08-29 17:28
This one, right?

![image](https://user-images.githubusercontent.com/54396528/63961911-0949ba80-cabc-11e9-8235-1d95f0c4378c.png)

The problem is pretty obvious I see, your code's missing the ")".

It's supposed to look like this, {\fad(1000,350)}

**Comment by RanHackett** [comment] 2019-08-30 03:53
Huh, strange, In the program it works just fine. And what about the random
space at the begin of the text, is that normal? (I think it happens because
I use {/move}, but not sure)

**Comment by arcusmaximus** [comment] 2019-08-31 12:30
As of YTSubConverter 1.4.0, {\fad(1000,350} (without a closing parenthesis) will work too.

For the random space: don't pay too much attention to the text in YouTube's builtin subtitle editor. What matters is that everything looks OK when previewing using Fiddler.

I should also mention that as of yesterday, self-approval of subtitles is no longer possible: https://twitter.com/TeamYouTube/status/1167565334917742593
You now *have* to get the channel owner to do the approval.

**Comment by RanHackett** [comment] 2019-08-31 16:13
Carp, that's gonna hurt us alot. Okay, then what about  Fiddler, I have
done setting it up but still not know how to "view" the caption

Vào Th 7, 31 thg 8, 2019 vào lúc 19:30 arcusmaximus <
notifications@github.com> đã viết:

**Comment by arcusmaximus** [comment] 2019-09-02 18:20
As long as Fiddler is active, any subtitles you view on YouTube will be replaced by the ones you have selected. This of course means you can only use it on videos that already have subtitles.

For videos that don't have any subtitles, you can't use Fiddler. In this case, you can upload an unlisted copy of the video to your own channel and test there.

**Comment by nyaasar** [comment] 2019-09-02 20:22
Oh great, now I know why my subs just layin' there with green "submitted" text instead of "published" on it.

Well, I guess I'll just need to wait for Youtube to change it's Community Contribution policy again.

**Closed** 2019-10-06 16:27 UTC
