### ISSUE TITLE
PSA: YouTube is planning to stop community subtitles on September 28

### ISSUE THREAD

**Issue by phly95** [arcusmaximus/YTSubConverter#21] opened 2020-08-02 05:38 UTC
People using this tool should voice their concerns about this wherever they can.
See this video for an explanation of what's going on https://www.youtube.com/watch?v=FgRB9dbWAH4

**Comment by phly95** [comment] 2020-08-04 06:57
One solution to this problem would be to create a browser extension that injects captions into the videos and host them elsewhere.

**Comment by arcusmaximus** [comment] 2020-08-04 07:24
It's not, really. First of all, most people would never even hear about the extension, and even if they did, chances are they'd be wary of installing it (or simply too lazy). And secondly, a browser extension doesn't help much in a time where a sizable portion of (if not most) viewers watch videos inside a mobile app.

**Comment by phly95** [comment] 2020-08-06 02:35
That's a good point. Maybe a hybrid approach would work. Have a site where creators can connect with their YouTube channel and automatically import fansubs, as well as having the option of client-side extension that works for channels that don't use that system.

So users that know about the extension get access to community subs, and creators have the opportunity to make them accessible for all platforms. This could be done using a third party website.

**Comment by arcusmaximus** [comment] 2020-08-06 16:13
I've thought about that too, but the problem is that YouTube doesn't offer an API for uploading subtitles. This means such a third party website would have to log in on YouTube and go through the UI on the creator's behalf, which in turn would mean the creator has to hand over their password to this third party website. Good luck convincing people to do that :p. Oh, and good luck protecting the passwords of the few people who do sign up. You can't hash them (because you need to send them to YouTube), so if and when the site gets hacked, people's passwords will be stolen and it'll be your fault.

No, the only way to continue making styled fansubs will be to send the .ytt to the creator and ask them to upload it for you.

**Comment by phly95** [comment] 2020-08-25 19:36
I saw some good news. YouTube is planning a “Editor (Limited) without Revenue” permission which would allow creators to give a trusted set of people access to editing the video information. This includes captions. So creators will have the option to collaborate with fansubbers in a new way that will keep the spirit of community captions alive to some extent. 

https://support.google.com/youtube/thread/61967856?hl=en&msgid=62009432

**Comment by arcusmaximus** [comment] 2020-08-26 07:22
Exactly. As you wrote, the role "will be able to edit **all** parts of a creator’s content" (emphasis mine), which is obviously too much to grant to some random stranger offering to do captions for you. So this is no solution either.

Besides, there's also the question how you'd apply for such a role in the first place. As you know, even with the current system it's hard to notify creators about subtitles you submitted; YouTube sure doesn't notify them, so you need to contact the owner yourself and hope they notice you. You might think YouTube learned from this and will introduce some sort of application system, but no:
https://www.youtube.com/watch?v=VMZSgqMa_uM&lc=UgxnHWmmTIg-qE2OdU14AaABAg.9BqKen1J9km9BudDLRvU6p
>  No plans for a notification system but using comments or the creators info in the about page will hopefully work. Note that with the switch to creators having to approve community captions they usually approve contributors they know so hopefully that process can work hear.

Notice how they didn't even consider what'll happen in the future, when new creators appear who never approved captions through the current system. Those creators won't know any captionists, so they also won't know who they can trust with the role.

And yet, despite making it even harder to send captions than it already is, YouTube is somehow, somehow, convinced that the new system will result in more captions, not (even) less. No matter how many people tell them otherwise.

**Comment by RubenArtmann** [comment] 2020-09-14 19:02
How about an addon which automates the importing of subtitles from a website? Then you only have to convince the creators to download/trust an (hopefully opensource) addon. (Or (ab)using Bookmarklets if downloading an addon is problematic)

**Comment by arcusmaximus** [comment] 2020-09-17 20:53
After a bit more research, I found out I was wrong - YouTube does, in fact, offer an API for uploading and deleting subtitles on someone's behalf. This means it'd be theoretically possible to create a website to which creators can grant control over their channel (and revoke that control at any time) without having to hand over their credentials. And while the website itself would have the power to change anything on the channel, it could decide which users to pass how much of that power. For example, even captionists marked as Trusted within the website would only get to change subtitles and nothing else - unlike the "Editor (Limited)" role provided by YouTube.

**Comment by arcusmaximus** [comment] 2020-09-30 12:43
The "Add subtitles/CC" menu item in the video player is gone, but the community subtitle UI is still available by manually browsing to https://www.youtube.com/timedtext_video?v=(video ID). I don't know if this is the first step of a complete removal or just YouTube doing the absolute minimum effort required. (It wouldn't be the first time; think of how they disabled community approval last year.)

Either way, considering they never reversed their decision to disable this accessibility tool right after the International Week of the Deaf, we at least _officially_ can't use community subtitles anymore. As such I'm closing this ticket.

**Closed by arcusmaximus** 2020-09-30 12:43 UTC

**Comment by arcusmaximus** [comment] 2020-09-30 18:52
Update: the above loophole no longer works. The page now says that community contributions for the video are disabled, even if they're not. (The dropdown for enabling community contributions is still there in YouTube Studio)

**Comment by llacb47** [comment] 2020-09-30 18:58
> Update: the above loophole no longer works. The page now says that community contributions for the video are disabled, even if they're not. (The dropdown for enabling community contributions is still there in YouTube Studio)

Wrong - it still works. 

`https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=zSJnsLDFMyo&lang=en&bl=cspv&ui=hd&ref=psf&tab=captions&ar=1601492030065&o=U`

**Comment by arcusmaximus** [comment] 2020-10-01 07:05
I see. The `timedtext_video` URL no longer works, but `timedtext_editor` does:
`https://www.youtube.com/timedtext_editor?action_mde_edit_form=1&v=<video ID>`
It even pops up the language selection dialog. Thank you for reporting.

**Comment by arcusmaximus** [comment] 2020-10-01 07:33
I updated the documentation page with this information.
