### ISSUE TITLE
Failed to load file: Specified argument was out of range

### ISSUE THREAD

**Issue by a-rabin** [arcusmaximus/YTSubConverter#44] opened 2021-09-29 14:52 UTC
Hello, 
So I was done with a subtitle and I was trying to export it but whenever I open the file on YTSubConverter I get this error:
`Failed to load file: Specified argument was out of range of valid values.`
`Parameter name: GetItemRectangle index out of range.`

This is the header of the .ass file.
```
`[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 368
PlayResY: 720

[Aegisub Project Garbage]
Audio File: /home/[username]/illegal minecraft video.mp4
Video File: /home/[username]/illegal minecraft video.mp4
Video AR Mode: 4
Video AR Value: 0.511111
Video Zoom Percent: 0.500000
Scroll Position: 1
Active Line: 7
Video Position: 1360`
```
any help?

**Comment by arcusmaximus** [comment] 2021-09-29 16:55
I pasted this header over the header of a test .ass file and loaded it in YTSubConverter, but didn't get the error. Could you post the complete file, or (if you don't want to share the whole content) a minimal file that also reproduces it?

Also, it looks like you're running the converter on Linux, but it's not (yet) officially supported there.

**Comment by a-rabin** [comment] 2021-09-30 08:26
okay so I clicked the Style Options on the converter and I opened the file and NOW it functions, with no error.
I don't understand what was going wrong though.

**Comment by arcusmaximus** [comment] 2021-09-30 15:15
I can only assume Mono doesn't like zero-height groupboxes. Anyway, I'll close this ticket then as it's not an issue on Windows. The Linux version I'm working on will be based on Gtk# so hopefully won't have this problem.

**Closed by arcusmaximus** 2021-09-30 15:15 UTC

**Comment by a-rabin** [comment] 2021-09-30 18:15
yeah. thank you for responding
